# Generated by Django 5.1.2 on 2024-11-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0003_user_email_user_home_address_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Instructor'}, related_name='courses', to='djangoProject1.user'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Default Course Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(default='Default Lab Name', max_length=100),
        ),
    ]
