# Generated by Django 5.1.2 on 2024-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0004_alter_course_instructors_alter_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='home_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='DefaultFirst', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='DefaultLast', max_length=50),
        ),
    ]
