# Generated by Django 5.1.2 on 2024-12-11 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0006_remove_course_instructors_lab_day_lab_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['TA', 'Instructor']}, related_name='courses', to='djangoProject1.user'),
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['TA', 'Instructor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='djangoProject1.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
