# Generated by Django 5.1.2 on 2024-12-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0007_remove_section_instructor_course_users_section_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='user',
            new_name='user',
        ),
    ]
