# Generated by Django 5.1.2 on 2024-12-09 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0008_rename_users_section_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['TA', 'Instructor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='djangoProject1.user'),
        ),
    ]
