# Generated by Django 5.1.2 on 2024-12-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0007_remove_section_instructor_course_users_section_user_and_more'),
        ('djangoProject1', '0009_remove_section_user_section_user'),
    ]

    operations = [
    ]
