# Generated by Django 5.1.2 on 2024-12-11 21:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject1', '0010_merge_20241211_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='day',
        ),
        migrations.AddField(
            model_name='section',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True),
        ),
    ]
